import BookInterface from '../../src/MainComponents/types/booksType';

const result: BookInterface[] = [
  {
    author_key: ['OL2632008A'],
    author_name: ['Raymond Chandler'],
    cover_edition_key: 'OL16230363M',
    cover_i: 7268475,
    edition_count: 115,
    first_publish_year: 1939,
    has_fulltext: true,
    ia: [
      'bigsleep0000kerr',
      'changmianbuxing0000chan',
      'legrandsommeil0000chan',
      'bigsleep0000chan_y1u5',
      'bigsleep0000chan_d3q5',
      'bigsleep0000chan_m2k7',
      'bigsleepthe00raym',
      'bigsleep0000chan',
      'bigsleep0000chan_j9p6',
      'raymondchandlero00chan',
      'bigsleep000chan',
      'bigsleep00raym',
      'bigsleep0000unse',
      'bigsleepfarewell0000chan',
      'bigsleepfarewel00chan',
    ],
    ia_collection_s:
      'americana;bostonuniversitylibraries-ol;cnusd-ol;dartmouthlibrary-ol;delawarecountydistrictlibrary;delawarecountydistrictlibrary-ol;inlibrary;internetarchivebooks;ithacacollege-ol;johnshopkins-ol;library_of_atlantis;popularchinesebooks;printdisabled;the-claremont-colleges-ol;tulsacc-ol;unb-ol;universityofarizona-ol;universityofcoloradoboulder-ol;universityofoklahoma-ol',
    key: '/works/OL15400582W',
    // "id": "/works/OL15400582W",
    language: ['spa', 'ita', 'ger', 'eng', 'chi', 'swe', 'pol', 'fre', 'por'],
    lending_edition_s: 'OL27083136M',
    lending_identifier_s: 'bigsleep0000kerr',
    public_scan_b: false,
    title: 'The Big Sleep',
  },
  {
    author_key: ['OL27695A'],
    author_name: ['Agatha Christie'],
    cover_edition_key: 'OL40281005M',
    cover_i: 12996529,
    edition_count: 111,
    first_publish_year: 1927,
    has_fulltext: true,
    ia: [
      'bigfour0000agat',
      'lesquatre0000agat',
      'bigfour0000chri_a4a6',
      'poiroteiquattro0000chri',
      'osquatrograndes0000chri',
      'lesquatre0000chri',
      'bigfourchriagat00chri',
      'loscuatrograndes0000chri',
      'bigfour00chri',
      'bigfour0000chri_t8b4',
      'bigfour0000chri',
      'bigfourchri00chri',
      'bigfourherculepo00chri',
      'bigfourherculepo0000chri',
      'bigfourherculepo0000chri_p0a0',
      'diegrossenvier00chri',
    ],
    ia_collection_s:
      'americana;delawarecountydistrictlibrary;delawarecountydistrictlibrary-ol;inlibrary;internetarchivebooks;library_of_atlantis;openlibrary-d-ol;printdisabled;rochester-ol',
    key: '/works/OL471947W',
    // "id": "/works/OL471947W",
    language: [
      'spa',
      'ita',
      'ger',
      'eng',
      'chi',
      'heb',
      'pol',
      'fre',
      'por',
      'ara',
    ],
    lending_edition_s: 'OL40281005M',
    lending_identifier_s: 'bigfour0000agat',
    public_scan_b: true,
    title: 'The Big Four',
  },
  {
    author_key: ['OL22258A'],
    author_name: ['James Patterson'],
    cover_i: 189358,
    edition_count: 47,
    first_publish_year: 1873,
    has_fulltext: true,
    ia: [
      'wielkizywilk0000patt',
      'hetuurvandewolf0000patt',
      'grandmechantloup0000patt_z1g4',
      'grandmechantloup0000patt_o1d2',
      'grandmechantloup0000patt_w3k4',
      'grandmechantloup0000patt',
      'bigbadwolfalexcr0000jame',
      'bigbadwolf0000patt',
      'bigbadwolf00patt',
      'bigbadwolf0000jame',
      'bigbadwolf0000patt_v2o9',
      'bigbadwolf0000patt_w9d2',
      'isbn_B000AI8L6M',
      'bigbadwolf0000j',
      'bigbadwolfnovel0000patt',
      'bigbadwo00patt',
      'bigbadwolfnove00patt',
      'bigbadwolf0000jame_m3q8',
      'bigbadwolftextla00patt',
      'bigbadwolfnovel00patt',
    ],
    ia_collection_s:
      'americana;delawarecountydistrictlibrary;delawarecountydistrictlibrary-ol;drakeuniversity-ol;goffstownlibrary-ol;inlibrary;internetarchivebooks;openlibrary-d-ol;printdisabled;salisburyfreelibrary-ol;spokanepubliclibrary-ol;stmaryscountylibrary;uni-ol',
    key: '/works/OL167179W',
    // "id": "/works/OL167179W",
    language: ['dut', 'pol', 'eng', 'fre'],
    lending_edition_s: 'OL38216254M',
    lending_identifier_s: 'wielkizywilk0000patt',
    public_scan_b: false,
    title: 'The Big Bad Wolf',
  },
  {
    author_key: ['OL12432984A'],
    author_name: ['Lincoln Peirce'],
    cover_edition_key: 'OL46629752M',
    cover_i: 13840903,
    edition_count: 39,
    first_publish_year: 2010,
    has_fulltext: false,
    key: '/works/OL34357614W',
    // "id": "/works/OL34357614W",
    language: ['eng'],
    public_scan_b: false,
    subtitle: 'This means war',
    title: 'Big Nate',
  },
];

export default result;
